apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ .Values.names.clusterRoleName }}
  labels:
    name: {{ .Values.names.clusterRoleName }}
  # "namespace" omitted since ClusterRoles are not namespaced
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources: [
    "events",
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps",
    "replicationcontrollers"
  ]
  verbs: [get, list]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources: [
    "events",
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps",
    "replicationcontrollers"
  ]
  verbs: [get, list]
- apiGroups:
  - extensions
  resources: [
    "events",
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps",
    "replicationcontrollers"
  ]
  verbs: [get, list]
- apiGroups:
  - apps
  resources: [
    "events",
    "pods",
    "services",
    "nodes",
    "nodes/proxy",
    "serviceaccounts",
    "namespaces",
    "resourcequotas",
    "daemonsets",
    "deployments",
    "replicasets",
    "statefulsets",
    "networkpolicies",
    "ingresses",
    "podsecuritypolicies",
    "roles",
    "rolebindings",
    "clusterroles",
    "clusterrolebindings",
    "cronjobs",
    "secrets",
    "configmaps",
    "replicationcontrollers"
  ]
  verbs: [get, list]
