apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sensor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sensor.labels" . | nindent 4 }}
    run: {{ include "sensor.fullname" . }}
